fix: Fix generateBoard function and call shuffle function from this function
LEARNING POINT: In for-loop use the [index] used IN the for-loop,
because that one will get looped, not another [index].

Error: Everything with class 'fa' will get affected by the randomizer.
See next commit for fix.